site_name: NiPreps
site_description: Augmenting neuroimaging acquisition devices to produce analysis-grade data
site_author: The NiPreps developers
site_url: https://www.nipreps.org
google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Repository
# repo_name: nipreps/nipreps.github.io
# repo_url: https://github.com/nipreps/nipreps.github.io

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: index.md
    - News and Announcements: news/index.md
    - NiPreps:
      - Framework: intro/nipreps.md
      - Transparency of workflows: intro/transparency.md
    - Community:
      - Welcome: community/index.md
      - Membership: community/members.md
      - New features: community/features.md
      - Contributing: community/CONTRIBUTING.md
      - Code of Conduct: community/CODE_OF_CONDUCT.md
      - Licensing: community/licensing.md
    - Documentation (users):
      - BIDS-Apps:
        - Introduction: apps/framework.md
        - Executing with Docker: apps/docker.md
        - Executing with Singularity: apps/singularity.md
      - Presentations: users/talks.md
      - Educational: users/educational.md
    - Documentation (devs):
      - Developer Environment: devs/devenv.md
      - Versions Matrix: devs/versions.md
      - Releases: devs/releases.md
theme:
  name: material
  features:
    - tabs
  favicon: assets/nipreps_brain.png
  logo: assets/nipreps_brain.png

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs

extra_css:
  - stylesheets/extra.css
