name: Update telemetry charts

on:
  push:
    branches: [mkdocs]

jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mkdocs
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update telemetry images
        run: |
          python scripts/update_telemetry_images.py
      - name: Commit changes
        run: |
          git config user.email "nipreps@gmail.com"
          git config user.name "nipreps-bot"
          if ! git diff --quiet; then
            git commit -am "auto: update telemetry charts"
            git push
          fi
